api:
    resource: "@APIBundle/Controller/"
    type:     rest
    prefix:   /api/v1

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc