version: '2'
services:
  web:
    image: nginx:latest
    ports:
     - "8080:80"
    volumes:
     - ./project:/project
     - ./docker/web/symfony.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:7.1-fpm
    volumes:
    - ./project:/project