version: '2'
services:
  web:
    image: nginx:latest
    ports:
     - "8080:80"
     - "8081:81"
    volumes:
     - ./backend:/backend
     - ./frontend:/frontend
     - ./docker/web/sites.conf:/etc/nginx/conf.d/default.conf

  php:
#    image: php:7.1-fpm
    build:
      context: ./docker/php
    volumes:
    - ./backend:/backend
#
#  node:
#      image: node:7.2
#      volumes:
#      - ./frontend:/frontend