version: '2'
services:
  web:
    image: nginx:latest
    ports:
     - "8080:80"
    volumes:
     - ./backend:/backend
     - ./docker/web/symfony.conf:/etc/nginx/conf.d/default.conf

  php:
#    image: php:7.1-fpm
    build:
      context: ./docker/php
    volumes:
    - ./backend:/backend